[package]
name = "client-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grpc = "~0.8"
protobuf = "2.23"
futures = "~0.3"

[build-dependencies]
protoc-rust-grpc = "~0.8"
